name: First Workflow

on:
  workflow_dispatch # This will make sure user will trigger workflow manually

jobs:
  first-job:
    runs-on:
      ubuntu-latest
    steps:
      - name: Greetings
        run: |
          echo "Hello World"
          echo "How are you doing?"
      - name: Goodbye
        run: echo "Done - Bye!"
